# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=10, verbose_name='颜色')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Colors'),
        ),
        migrations.AddField(
            model_name='child',
            name='favor',
            field=models.ManyToManyField(to='cmdb.Colors'),
        ),
        migrations.AddField(
            model_name='ball',
            name='color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Colors'),
        ),
    ]
